name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  unlighthouse:
    name: Run unlighthouse
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
        run: npx unlighthouse-ci

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ".unlighthouse"
          destination-github-username: "sharjeelabbas014"
          destination-repository-name: "unlighthouse-depl"
          user-email: sharjeelabbas014@gmail.com
          target-branch: main
