name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  unlighthouse:
    name: Run unlighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
        run: npx unlighthouse-ci

      - name: Build static site
        # Replace this with the command to build your static site using your preferred generator
        run: cd .unlighthouse
